SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[func_TRIM] (@Input NVARCHAR(4000))
RETURNS NVARCHAR(4000) 
AS 
BEGIN
       SET @Input = RTRIM(LTRIM(@Input))
       RETURN @Input
END
GO
