SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[func_MAX_DATETIME](@Date1 DATETIME, @Date2 DATETIME)
RETURNS DATETIME
AS BEGIN

	IF @Date1 > @Date2 BEGIN
		RETURN @Date1
	END
	RETURN COALESCE(@Date2,@Date1,'1/1/1900')

END
GO
