SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[func_NullIfNaN](@Value VARCHAR(100))
	RETURNS FLOAT
AS BEGIN

	IF ISNUMERIC(@Value + 'e0') = 1
		RETURN CAST(@Value AS FLOAT)
	RETURN NULL
END
GO
