CREATE TABLE [dbo].[tbl_ReportGroupPeriodResult]
(
[ReportGroupPeriodResultID] [int] NOT NULL,
[ReportGroupID] [int] NOT NULL,
[ReportGroupPeriodID] [int] NOT NULL,
[ReportGroupMetricID] [int] NOT NULL,
[MetricID] [int] NOT NULL,
[CalculationID] [int] NOT NULL,
[CategoryID] [int] NOT NULL,
[SourceID] [int] NOT NULL,
[ApplicationID] [int] NOT NULL,
[AggregationID] [int] NOT NULL,
[ReportGroupName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PeriodBeginDate] [datetime] NOT NULL,
[PeriodEndDate] [datetime] NOT NULL,
[MetricName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MetricDescription] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NumeratorDescription] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DenominatorDescription] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CategoryName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ApplicationName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AggregationName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BenefitYearFlag] [bit] NOT NULL,
[M1] [float] NULL,
[M2] [float] NULL,
[M3] [float] NULL,
[M4] [float] NULL,
[M5] [float] NULL,
[M6] [float] NULL,
[M7] [float] NULL,
[M8] [float] NULL,
[M9] [float] NULL,
[M10] [float] NULL,
[M11] [float] NULL,
[M12] [float] NULL,
[Q1] [float] NULL,
[Q2] [float] NULL,
[Q3] [float] NULL,
[Q4] [float] NULL,
[YTD] [float] NULL,
[AddedDate] [datetime] NOT NULL,
[DeletedDate] [datetime] NULL
) ON [PRIMARY]
GO
