CREATE TABLE [pepsico].[Incentives_ReportLog]
(
[ReportLogID] [int] NOT NULL IDENTITY(1, 1),
[MemberID] [int] NOT NULL,
[EligMemberID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligMemberSuffix] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelationshipID] [int] NULL,
[Birthdate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailAddress] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS4] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS5] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS6] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS8] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS13] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS14] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS15] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS16] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityItemCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ActivityDate] [datetime] NOT NULL,
[Amount] [int] NOT NULL,
[MessageCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stratification] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateReported] [datetime] NOT NULL,
[ReportedTo] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ReportEndDate] [datetime] NULL,
[AddedDate] [datetime] NOT NULL,
[AddedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rerun] [bit] NOT NULL,
[Activity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Deleted] [bit] NOT NULL,
[OldMemberID] [int] NULL,
[IsWaiver] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [pepsico].[Incentives_ReportLog] ADD CONSTRAINT [PK_ReportLogID] PRIMARY KEY CLUSTERED  ([ReportLogID]) ON [PRIMARY]
GO
