CREATE TABLE [pepsico].[CrossReferral_ReportLog]
(
[ReportLogID] [int] NOT NULL IDENTITY(1, 1),
[MemberID] [int] NOT NULL,
[EligMemberID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS5] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS9] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS11] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHACompletionDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BioCompletionDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LMIncentiveEligible] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LMIncentiveMet] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BioLMStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BioLMStatusDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TobaccoSurchargeApplied] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TobaccoCessationStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TobaccoCessationStatusDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PregnancyIndicator] [int] NULL,
[DateReported] [datetime] NOT NULL,
[ReportedTo] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AddedDate] [datetime] NOT NULL,
[AddedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedDate] [datetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rerun] [bit] NOT NULL,
[OUTCOMES] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COACHING] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LMCOACHINGSCHED] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LMCOACHINGLAST] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LMCOACHINGFOUR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LMCOACHINGCOUNT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LMCOACHINGENROLL] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOBCOACHINGSCHED] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOBCOACHINGLAST] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOBCOACHINGFOUR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOBCOACHINGCOUNT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOBCOACHINGENROLL] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OUTREACH] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DECLINEUNABLE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OUTREACHCOUNT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [pepsico].[CrossReferral_ReportLog] ADD CONSTRAINT [PK_ReportLogID_CrossRef] PRIMARY KEY CLUSTERED  ([ReportLogID]) ON [PRIMARY]
GO
